commands_restrictions:
  update:
    conditions:
      - sender = livastic-vm4-primary-20260911

pull_request_rules:
  - name: vm4 head rename freshness update 250925
    conditions:
      - head = vm4-safe-head-rename-240924
      - label = vm4-head-rename-go-240924
    actions:
      update: {}
