merge_queue:
  queue_controls_comment: false

queue_rules:
  - name: vm4-native-protection-freshness-240924
    queue_conditions: []
    merge_conditions:
      - status-success = vm4-release-native-protection-240924
    branch_protection_injection_mode: merge
    merge_method: merge
    batch_size: 1
    batch_max_wait_time: "1 second"
    checks_timeout: null
